[package]
name = "rust_program"
version = "0.1.0"
edition = "2021"



[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
once_cell = "1.8.0"
clap = "3.1.6"